export enum QuestionType {
  SHORT_ANSWER = 'SHORT_ANSWER',
  LONG_ANSWER = 'LONG_ANSWER',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CHECKBOXES = 'CHECKBOXES',
  DROP_DOWN = 'DROP_DOWN',
  LINEAR_SCALE = 'LINEAR_SCALE',
  RADIO_GRID = 'RADIO_GRID',
  CHECKBOX_GRID = 'CHECKBOX_GRID',
  DATE_ANSWER = 'DATE_ANSWER',
  TIME_ANSWER = 'TIME_ANSWER',
  FILE_UPLOAD = 'FILE_UPLOAD',
  ADDRESS_ANSWER = 'ADDRESS_ANSWER',
}

